-- ============================================================================
-- V3: external-facing public ids (hybrid id strategy)
-- BIGINT stays the internal PK / FK / join key. public_id is what APIs and URLs
-- expose: non-enumerable (no IDOR-by-probing) and hides row volume.
-- Value is a UUIDv7 generated by the app (Hibernate @UuidGenerator(style = TIME))
-- so it stays time-ordered and index-friendly. No DB-side uuidv7() default here,
-- to keep the migration portable to PostgreSQL 13+ (uuidv7() is PG18-only).
-- NOT NULL with no default is safe: these tables are empty at this migration.
-- ============================================================================

ALTER TABLE users         ADD COLUMN public_id UUID NOT NULL;
ALTER TABLE events        ADD COLUMN public_id UUID NOT NULL;
ALTER TABLE bookings      ADD COLUMN public_id UUID NOT NULL;
ALTER TABLE booking_items ADD COLUMN public_id UUID NOT NULL;

ALTER TABLE users         ADD CONSTRAINT uq_users_public_id         UNIQUE (public_id);
ALTER TABLE events        ADD CONSTRAINT uq_events_public_id        UNIQUE (public_id);
ALTER TABLE bookings      ADD CONSTRAINT uq_bookings_public_id      UNIQUE (public_id);
ALTER TABLE booking_items ADD CONSTRAINT uq_booking_items_public_id UNIQUE (public_id);
