-- ============================================================================
-- EventHub baseline schema (V1)
-- PostgreSQL. Enum-like columns use VARCHAR + CHECK so JPA @Enumerated(STRING)
-- maps 1:1 later. Surrogate keys: BIGINT identity. Timestamps: timestamptz.
-- Money: numeric(12,2); aggregated revenue: numeric(14,2).
-- FK rules: reference/financial data RESTRICT; owned child rows CASCADE.
-- ============================================================================

-- gen_random_uuid() is core in PG13+; extension keeps older servers working.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Identity & access
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
         CHECK (name IN ('CUSTOMER', 'ORGANIZER', 'ADMIN'))
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE organizers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    org_name   VARCHAR(255) NOT NULL,
    verified   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- Venues & seating
-- ---------------------------------------------------------------------------
CREATE TABLE venues (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    layout_type VARCHAR(20)  NOT NULL
                CHECK (layout_type IN ('STADIUM', 'THEATER', 'CONFERENCE_HALL', 'OPEN_GROUND')),
    address     VARCHAR(255),
    city        VARCHAR(120),
    created_at  TIMESTAMPTZ,
    updated_at  TIMESTAMPTZ
);

CREATE TABLE sections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id   BIGINT       NOT NULL REFERENCES venues (id) ON DELETE CASCADE,
    name       VARCHAR(120) NOT NULL,
    seat_type  VARCHAR(15)
               CHECK (seat_type IN ('REGULAR', 'VIP', 'PREMIUM', 'ACCESSIBLE')),
    base_price NUMERIC(12, 2),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT      NOT NULL REFERENCES sections (id) ON DELETE CASCADE,
    row_label  VARCHAR(10) NOT NULL,
    col_number INTEGER     NOT NULL,
    status     VARCHAR(10) NOT NULL DEFAULT 'FREE'
               CHECK (status IN ('FREE', 'HELD', 'BOOKED')),
    version    BIGINT      NOT NULL DEFAULT 0,   -- optimistic-lock token
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_seat_position UNIQUE (section_id, row_label, col_number)
);
-- Hot path: "free seats in a section" and group-allocation scans.
CREATE INDEX idx_seat_section_status ON seats (section_id, status);

-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL UNIQUE
);

CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT       NOT NULL REFERENCES organizers (id) ON DELETE RESTRICT,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    category_id  BIGINT       REFERENCES categories (id) ON DELETE SET NULL,
    venue_id     BIGINT       REFERENCES venues (id) ON DELETE RESTRICT,
    city         VARCHAR(120),
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION,
    starts_at    TIMESTAMPTZ,
    ends_at      TIMESTAMPTZ,
    status       VARCHAR(15)  NOT NULL DEFAULT 'DRAFT'
                 CHECK (status IN ('DRAFT', 'ON_SALE', 'CLOSED', 'CANCELLED')),
    high_demand  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ
);
-- Browse/listing: on-sale events ordered by start time.
CREATE INDEX idx_event_status_starts ON events (status, starts_at);

CREATE TABLE event_tags (
    event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, tag_id)
);

CREATE TABLE event_images (
    event_id BIGINT       NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    url      VARCHAR(512) NOT NULL
);
CREATE INDEX idx_event_images_event ON event_images (event_id);

CREATE TABLE ticket_types (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT        NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    name       VARCHAR(120)  NOT NULL,
    price      NUMERIC(12, 2) NOT NULL,
    quota      INTEGER       NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- Booking & payment
-- ---------------------------------------------------------------------------
CREATE TABLE bookings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    event_id   BIGINT         NOT NULL REFERENCES events (id) ON DELETE RESTRICT,
    status     VARCHAR(15)    NOT NULL DEFAULT 'PENDING'
               CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED')),
    total      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_booking_user  ON bookings (user_id);
CREATE INDEX idx_booking_event ON bookings (event_id);

CREATE TABLE booking_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    seat_id        BIGINT         NOT NULL REFERENCES seats (id) ON DELETE RESTRICT,
    ticket_type_id BIGINT         REFERENCES ticket_types (id) ON DELETE SET NULL,
    price          NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    -- a seat can appear in at most one booking item (no double-sell)
    CONSTRAINT uq_booking_item_seat UNIQUE (seat_id)
);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE RESTRICT,
    amount          NUMERIC(12, 2) NOT NULL,
    status          VARCHAR(15)    NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    provider_ref    VARCHAR(255),
    idempotency_key VARCHAR(80)    UNIQUE,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ
);

CREATE TABLE refunds (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT         NOT NULL REFERENCES payments (id) ON DELETE RESTRICT,
    amount     NUMERIC(12, 2) NOT NULL,
    status     VARCHAR(15)    NOT NULL DEFAULT 'REQUESTED'
               CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    reason     VARCHAR(512),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- Engagement
-- ---------------------------------------------------------------------------
CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT  NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    user_id    BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating     INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    body       TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_review_event ON reviews (event_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(30) NOT NULL
               CHECK (type IN ('BOOKING_CONFIRMED', 'PAYMENT', 'REFUND', 'EVENT_UPDATE', 'SYSTEM')),
    payload    JSONB,
    is_read    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_notification_user_unread ON notifications (user_id) WHERE is_read = FALSE;

-- ---------------------------------------------------------------------------
-- Reliability: transactional outbox + idempotency
-- ---------------------------------------------------------------------------
CREATE TABLE outbox_events (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type VARCHAR(40)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(60)  NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(15)  NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at   TIMESTAMPTZ
);
-- Relay scans only unprocessed rows, oldest first.
CREATE INDEX idx_outbox_unprocessed ON outbox_events (created_at) WHERE processed_at IS NULL;

CREATE TABLE idempotency_keys (
    idem_key     VARCHAR(80)  PRIMARY KEY,
    request_hash VARCHAR(128) NOT NULL,
    response     JSONB,
    status       VARCHAR(15)  NOT NULL,   -- IN_PROGRESS | COMPLETED
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ
);
CREATE INDEX idx_idempotency_expires ON idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------
-- Analytics projections (maintained by the analytics consumer)
-- ---------------------------------------------------------------------------
CREATE TABLE event_stats (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT           NOT NULL UNIQUE REFERENCES events (id) ON DELETE CASCADE,
    tickets_sold   BIGINT           NOT NULL DEFAULT 0,
    revenue        NUMERIC(14, 2)   NOT NULL DEFAULT 0,
    occupancy_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ
);

CREATE TABLE daily_sales (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT         NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    sales_date    DATE           NOT NULL,
    tickets_count BIGINT         NOT NULL DEFAULT 0,
    revenue       NUMERIC(14, 2) NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT uq_daily_sales UNIQUE (event_id, sales_date)
);
